// src/servicesConfig.js

module.exports = {
  AUTH_SERVICE: 'http://auth-service:3000',
  REGISTRATION_SERVICE: 'http://registration-service:8082',
  USER_PROFILE_SERVICE: 'http://user-profile-service:3001',
  ROLE_SERVICE: 'http://role-service:3012',
  USER_PREFERENCES_SERVICE: 'http://user-preferences-service:3013',
  SESSION_SERVICE: 'http://session-service:3014',
  PET_PROFILE_SERVICE: 'http://pet-profile-service:3003',
  PET_HEALTH_SERVICE: 'http://pet-health-service:3009',
  PET_MATCHING_SERVICE: 'http://pet-matching-service:3017',
  PET_PREFERENCES_SERVICE: 'http://pet-preferences-service:3015',
  PET_EVENT_SERVICE: 'http://pet-event-service:3016',
  SHELTER_SERVICE: 'http://shelter-service:3018',
  DONATION_SERVICE: 'http://donation-service:3019',
  GEO_SERVICE: 'http://geo-service:3026',
  POST_SERVICE: 'http://post-service:3006',
  COMMENT_SERVICE: 'http://comment-service:3007',
  LIKE_SERVICE: 'http://like-service:3020',
  MEDIA_SERVICE: 'http://media-service:3008',
  STORY_SERVICE: 'http://story-service:3021',
  FEED_SERVICE: 'http://feed-service:3010',
  SEARCH_SERVICE: 'http://search-service:3025',
  CHAT_SERVICE: 'http://chat-service:3004',
  NOTIFICATION_SERVICE: 'http://notification-service:3005',
  EMAIL_SERVICE: 'http://email-service:3022',
  REPORT_SERVICE: 'http://report-service:3011',
  AUDIT_SERVICE: 'http://audit-service:3029',
  LOG_SERVICE: 'http://log-service:3023',
  TRANSLATION_SERVICE: 'http://translation-service:3027',
  MONITORING_SERVICE: 'http://monitoring-service:3024',
};
